### ISSUE TITLE
[Bug] Infested Beds are Invisible

### ISSUE THREAD

**Issue by Jusey1** [MehVahdJukaar/sleep_tight#11]
Quick Video:

https://user-images.githubusercontent.com/61861078/225420094-023b9876-ce6b-493d-96f0-79770c4475c3.mp4

I'm not sure if this is just a server/client weirdness bug since I am showing this while I'm on my server but yeah... I'll look more into it. As far as I know though, at least everything works just fine gameplay wise.

**Comment by Jusey1** [comment]
It is!

**Comment by sombrae** [comment]
I'm having this same problem, using the lastest mod version.

I also discovered a couple other bugs; two bedbugs can go into the same bed, and that bed won't be able to "heal". Also, beds from the Clutter mod aren't being targeted by bedbugs. Since you mentioned in the Curseforge page that "If that mod adds new beds all should work fine", I also wanted to tell you this.

https://streamable.com/kik2jz
