### ISSUE TITLE
moonlight config issue

### ISSUE THREAD

**Issue by Boroso** [MehVahdJukaar/sleep_tight#28]
i think if i change sleeptight config too much, it doesnt keep me from starting the curseforge launcher, 1.19.2 fabric latest sleeptight version as of current, latest fabric api and version as of current and its surely an issue with config by moonlight or sleeptight, i hope it gets fixed so i can add it to my server

**Comment by MehVahdJukaar** [comment]
Send me the log when that happens

**Comment by Boroso** [comment]
mm ye goodluck, i think the issue is somewhere here anyway

**Comment by MehVahdJukaar** [comment]
I can't help nor fix without a log

**Comment by Boroso** [comment]
As I said, goodluck

**Comment by MehVahdJukaar** [comment]
Good luck for what? It's an issue you are having and as I've said I can't do anything if you don't provide me with the required information. Plus I realized your original description doesn't even make sense. Mods have nothing to do the the cueseforge application. At most it would either be a cueseforge issue or more likely you meant that it crashes your game, that's why I asked for the log

**Comment by Boroso** [comment]
why do u need me to explain it to u, just test ur goofy mod a bit by changing the configs and u'll get the crash with 'moonlight' in it, try testing ur stuff mate, specifically set '"max_angle": 100.0"' to '"max_angle": 80.0', if u're still gonna argue u can just close this rn

**Comment by MehVahdJukaar** [comment]
I cant relicate. I set that config to 80 and the game boots up fine.
Had you sent me your logs like I asked you instead of being smart and entitled sending stuff like "good luck" i would have told you ages ago exactly what the problem was of if the mod was actually bugged.
Given the very limited info i have I'll just conclude that you put some invalid characteds like commas or spaces in the configs so that's why it wasnt loading as the config itself had been improperly changed

**Comment by Boroso** [comment]
wth, i wasn't acting smart but i was annoyed because as soon as u were just trying to argue without me thinking that you aren't testing anything, therefore i gave u the goodluck treatment, but now you provided a solution and proved my conclusion wrong, so all good and thank you for correcting my invalid character mistake, i like your mod and thats why i tried to point the issue that i thought was happaning after you kept arguing with me, goodjob :D
