### ISSUE TITLE
Latest version on 1.20.1 crashes because of a conflict with Supplementaries

### ISSUE THREAD

**Issue by Tsunamori74** [MehVahdJukaar/sleep_tight#81]
The log says Sleep Tight is loading a banner pattern too early and making the game crash on world load.

**Comment by MehVahdJukaar** [comment]
It says the opposite actually. It says that some mod broke all modded banner patterns. I put that message there specifically to protect my own patterns such as the ones in sleep tight since it seems modders like to nuke that class

**Comment by Tsunamori74** [comment]
Man you’re gating out most of Fabric content mods to preserve the existence of 1 singular banner pattern. If every mod messes up that one banner pattern maybe you should look into implementing in a different way. It’s unlikely you’re the only one doing things right and everyone else is doing it wrong. So far I’ve had the crash with oreganized, bewitchment, excessive building, hexalia, the list goes on. Sorry for ranting but it’s really frustrating.

**Comment by MehVahdJukaar** [comment]
most fabric content? i could add a pattern to supplementaries and that too would be considered affected. You have a mod that breaks that stuff. its their bug. I had to put this shit there becuase forge log wasnt strong enough  and I was getting and fabrid didnt have anything at all. This really is a vanilla rchitecture issue which mods can very very easily break fi they arent careful.

Oh finally I just tested with sleep right, supplementaries, oreganized and excessive building and i did not have any issue at all.
You definitely have some mod that is messing stuff up 
Also confused because first you tal about fabric the talk about oreganized which is NOT a fabric mod
